language: csharp

solution: web_api_2.sln

notifications:

 email:

   on_success: always

   on_failure: always

 slack: srboeingdotnet:pZz5KfrgntyjLpS9a1d2b1rH

mono: none

dotnet: 2.1

script:

 - dotnet restore
 - dotnet test web/